name: test1
run-name: test1 triggered bt ${{ github.actor }}
on:
  label:
    types:
      - created
      - edited
      - deleted
  push:
    branches:
      - main
  schedule:
    - cron: "14 1 * * *"
jobs:
  comiple:
    name: Comiple
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: print a greeting
        env:
          MY_NAME: ${{ github.actor }}
        run: echo Hi, $MY_NAME
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Comiple code
        run: gcc -Wall -Wextra walawala.c -o walawala
      - name: Run test1
        run: echo "5" | ./walawala | grep -q "10" && echo "Accepted" || (echo "Unaccepted"; exit 1)
  test1:
    needs: comiple
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run test1
        run: echo "5" | ./walawala | grep -q "10" && echo "Accepted" || (echo "Unaccepted"; exit 1)
      - name: Run test2
        run: echo "0" | ./walawala | grep -q "0" && echo "Accepted" || (echo "Unaccepted"; exit 1)
      - name: Run test3
        run: echo "-1243" | ./walawala | grep -q "-2486" && echo "Accepted" || (echo "Unaccepted"; exit 1)
    
