name: test a.py
run-name: test1 triggered bt ${{ github.actor }}
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  label:
    types:
      - created
      - edited
      - deleted
  push:
    branches:
      - main
      - test_ci
  schedule:
    - cron: "14 1 * * *"
jobs:
  greeting-bash:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo Hi, ${{ github.actor }}

  greeting-powershell:
    runs-on: windows-latest
    steps:
      - run: echo Hi, ${{ github.actor }}
  
  test-ubuntu:
    if: ${{ always() }}
    needs: greeting-bash
    name: Compile in ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run test1
        run: bash -c 'echo "5" | python a.py | grep -q "10" && echo "Accepted" || (echo "Unaccepted"; exit 1)'
      - name: Run test2
        run: bash -c 'echo "0" | python a.py | grep -q "0" && echo "Accepted" || (echo "Unaccepted"; exit 1)'
      - name: Run test3
        run: bash -c 'echo "-1243" | python a.py | grep -q -- "-2486" && echo "Accepted" || (echo "Unaccepted"; exit 1)'
  test-macos:
    if: ${{ always() }}
    needs: greeting-bash
    name: Compile in macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run test1
        run: echo "5" | python a.py | grep -q "10" && echo "Accepted" || (echo "Unaccepted"; exit 1)
      - name: Run test2
        run: echo "0" | python a.py | grep -q "0" && echo "Accepted" || (echo "Unaccepted"; exit 1)     
      - name: Run test3
        run: echo "-1243" | python a.py | grep -q -- "-2486" && echo "Accepted" || (echo "Unaccepted"; exit 1)
  test-windows:
    if: ${{ always() }}
    needs: greeting-powershell
    name: Compile in windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run test1
        run: if (echo "5" | python a.py | Select-String "10") { "Accepted" } else { "Unaccepted"; exit 1 }
      - name: Run test2
        run: if (echo "0" | python a.py | Select-String "0") { "Accepted" } else { "Unaccepted"; exit 1 }
      - name: Run test3
        run: if (echo "-1243" | python a.py | Select-String "-2486") { "Accepted" } else { "Unaccepted"; exit 1 }
